[package]
name = "example_server"
version = "0.1.0"
edition = "2024"


[dependencies]
axum = { version = "0.8.4", features = ["http2"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
